# Generated by Django 2.0.5 on 2018-05-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('score', models.PositiveIntegerField()),
                ('stage', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '인내의 숲 점수',
                'verbose_name_plural': '인내의 숲 점수들',
                'db_table': '스코어보드',
            },
        ),
    ]
